apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: muchtodo
type: Opaque
data:
  mongo-root-username: cm9vdA==
  mongo-root-password: ZXhhbXBsZQ==
  mongo-database: bXVjaF90b2RvX2Ri