apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
data:
  jwt-secret-key: eW91ci1zdXBlci1zZWNyZXQta2V5LXRoYXQtaXMtbG9uZy1hbmQtcmFuZG9t
  mongo-uri: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nb2RiLXNlcnZpY2U6MjcwMTcvbXVjaF90b2RvX2RiP2F1dGhTb3VyY2U9YWRtaW4=