apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb:27017"
  JWT_SECRET_KEY: "your-super-secret-key-that-is-long-and-random"